### ISSUE TITLE
Please update netmd-js to support Victor SS-NT1MD.

### ISSUE THREAD

**Issue by aaronamm** [cybercase/netmd-js#38]
Hello everyone,

My friend has just got **Victor SS-NT1MD** which is a Net MD component set.
However, Web MiniDisc does not support it.

I added a venderId and deviceId of this model to `netmd.ts` file with the following code:
```ts
    { vendorId: 0x04F1, deviceId: 0x6101, name: 'Victor SS-NT1MD' },
```

It works well with `yarn run cli devices` (I have updated the project on my local computer to use Yarn) and shows the connected device name as:
```pwsh
PS C:\projects\netmd-js> yarn cli devices      
yarn run v1.22.15
$ ts-node src/cli.ts devices
Found Device: Victor SS-NT1MD
Done in 3.28s.
```
However, when I tried to wipe a disc with `yarn cli wipe --verbose`, I got this error message.

```
NetMDRejected [Error]: Rejected
    at NetMDRejected.NetMDError [as constructor] (C:\projects\netmd-js\src\netmd-interface.ts:128:9)
    at new NetMDRejected (C:\projects\netmd-js\src\netmd-interface.ts:140:9)
    at NetMDInterface.<anonymous> (C:\projects\netmd-js\src\netmd-interface.ts:314:23)
    at step (C:\projects\netmd-js\src\netmd-interface.ts:46:23)
    at Object.next (C:\projects\netmd-js\src\netmd-interface.ts:27:53)
    at fulfilled (C:\projects\netmd-js\src\netmd-interface.ts:18:58)
error Command failed with exit code 1.
```

The NetMDRejected exception was thrown when reading a reply status in 
https://github.com/cybercase/netmd-js/blob/master/src/netmd-interface.ts#L314

In addition, I couldn't upload a raw music file to the device and got the same error message as:
```
NetMDRejected [Error]: Rejected
    at NetMDRejected.NetMDError [as constructor] (C:\projects\netmd-js\src\netmd-interface.ts:128:9)
    at new NetMDRejected (C:\projects\netmd-js\src\netmd-interface.ts:140:9)
    at NetMDInterface.<anonymous> (C:\projects\netmd-js\src\netmd-interface.ts:314:23)
    at step (C:\projects\netmd-js\src\netmd-interface.ts:46:23)
    at Object.next (C:\projects\netmd-js\src\netmd-interface.ts:27:53)
    at fulfilled (C:\projects\netmd-js\src\netmd-interface.ts:18:58)
error Command failed with exit code 1.
```

I think adding a venderId and deviceId is not enough, we may need to deal with a low level API to get this work.
I hope you can help to me get `Victor SS-NT1MD` works with netmd-js.
Thank you so much.

FYI, here is a picture of Victor SS-NT1MD.
<img width="743" alt="277458684_401921838438468_1179207107126513485_n" src="https://user-images.githubusercontent.com/2938310/161880361-b5f63979-143d-482c-b718-274f8f578e2b.png">

CC @asivery

**Comment by aaronamm** [comment]
@asivery I have collected more logging information from `wipe` and `upload` commands by uncomment these lines:
- https://github.com/cybercase/netmd-js/blob/master/src/query-utils.ts#L13
- https://github.com/cybercase/netmd-js/blob/master/src/query-utils.ts#L79-L90

and here are the logging messages:

For `wipe` command:

```pwsh
ps> node dist/cli.js wipe --verbose
SENT>>> F:  1840 ff 0000
```

For `upload` command:
```pwsh
ps> node dist/cli.js upload raw-audio.raw --format sp --verbose
SENT>>> F:  1808 80 00 01 00
SENT>>> F:  1809 8001 0230 8800 0030 8804 00 ff00 00000000
<<<RECV F:  1809 8001 0230 8800 0030 8804 00 1000 00090000 %x
<<<RECV D:  1809 8001 0230 8800 0030 8804 00 1000 00090000 00078804000340ff00
SENT>>> F:  1808 80 00 00 00
SENT>>> F:  1808 80 00 01 00
SENT>>> F:  1809 8001 0330 %w 0030 8805 0030 %w 00 ff00 00000000
<<<RECV F:  1809 8001 0330 %?%? %?%? %?%? %?%? %?%? %? 1000 00%?0000 %x %?
<<<RECV D:  1809 8001 0330 8802 0030 8805 0030 8806 00 1000 00080000 00 0688060003c5ff
SENT>>> F:  1808 80 00 00 00
SENT>>> F:  1808 80 00 01 00
SENT>>> F:  1809 8001 0430 8802 0030 8805 0030 0003 0030 0002 00 ff00 00000000
<<<RECV F:  1809 8001 0430 %?%? %?%? %?%? %?%? %?%? %?%? %?%? %? %?00 00%?0000 000b 0002 0007 00 %w %b %b %b %b
<<<RECV D:  1809 8001 0430 8802 0030 8805 0030 0003 0030 0002 00 1000 000d0000 000b 0002 0007 00 0000 00 03 35 00
SENT>>> F:  1808 80 00 00 00
SENT>>> F:  1800 080046 f0030103 21 ff 000000
SENT>>> F:  ff 010c ffff ffff ffff ffff ffff ffff
<<<RECV F:  ff 010c ffff ffff ffff ffff ffff ffff
<<<RECV D:  ff 010c ffff ffff ffff ffff ffff ffff
SENT>>> F:  1800 080046 f0030103 2b ff %w
<<<RECV F:  1800 080046 f0030103 2b 00 %?%?
<<<RECV D:  1800 080046 f0030103 2b 00 0001
SENT>>> F:  1800 080046 f0030103 80 ff
<<<RECV F:  1800 080046 f0030103 80 00
<<<RECV D:  1800 080046 f0030103 80 00
SENT>>> F:  1800 080046 f0030103 11 ff
<<<RECV F:  1800 080046 f0030103 11 00 %*
<<<RECV D:  1800 080046 f0030103 11 00 010000248aba0000
SENT>>> F:  1800 080046 f0030103 12 ff %w %d %d %d %d 00000000 %* %*
<<<RECV F:  1800 080046 f0030103 12 01 %?%? %?%?%?%?
<<<RECV D:  1800 080046 f0030103 12 00 0048 00000048
```
I hope this information is helpful for debugging and getting netmd-js support Victor MD device.
Thanks
